#Documentation:
#  Enabled: false
#
# Metrics/MethodLength:
#   Max: 15

Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: false

Style/FrozenStringLiteralComment:
  # Strings in Ruby 2.3 >= are frozen by default
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  CountComments: false  # count full line comments?
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/StderrPuts:
  Enabled: false
