root_keys:
  require:
    language:
      accepted_types:
        - String
    before_install:
      accepted_types:
        - String
        - Array
    install:
      accepted_types:
        - String
        - Array
    script:
      accepted_types:
        - String
        - Array
    jenkins:
      subkeys:
        required:
          secrets_id:
            accepted_types:
              - String
          secrets:
            subkeys:
              required:
                key:
                  accepted_types:
                    - String
                secret:
                  accepted_types:
                    - String
    pipeline:
      subkeys:
        required:
          script:
            subkeys:
              required:
                stage:
                  accepted_types:
                    - String
                steps:
                  subkeys:
                    required:
                      input:
                        subkeys:
                          required:
                            message:
                              accepted_types:
                                - String
  optiona:
    rvm:
      accepted_types:
        - String
